### ISSUE TITLE
Top 3 favorite Open Source Projects?

### ISSUE THREAD

**Issue by una** [ChrisMissal/ama#10]
Because choosing one is too diffcult

**Comment by ChrisMissal** [comment]
Wow, what a great question @una! For as much as I love open source software, I don't think I've ever tried to rank the projects in any kind of order. This got me thinking...

How does one judge what makes a project "top"? Rather than even limiting myself to three I thought I'd go on a rampage and list various ways I might rate those top three. I could base it on several factors:
1. What are my favorite projects to work on?
2. Which ones do I like to use the most?
3. What are the projects that have been most beneficial to me?
4. Which projects have I been a part of that are most beneficial to others?

I'm going to answer these in the moment. They could change next year or even tomorrow, but here we go:

## My Favorite Projects to Work On
1. [RoundhousE](http://github.com/chucknorris/roundhouse) – I've been using RH for a long, long time and it has made my experience working with databases so much nicer! I recently started helping out with maintenance, while challenging, it's still rewarding to see the project stay alive and healthy.
2. [Quiche](http://github.com/chrismissal/quiche) – This one might only be used by me, but I really like(d) building it and working on it.
3. [Cake](http://github.com/cake-build/cake) – This one is still new to me, but it's been an absolute pleasure working on. Great group of contributors and excellent code/docs/etc.

## The Projects I Most Enjoy Using
1. [HuBot](http://github.com/github/hubot) – My coworkers and I frequently add useful and goofy scripts for HuBot in our HipChat rooms. It's a lovely API and super easy and fun to work with.
2. [React](https://github.com/facebook/react) – React has worked very well so far with the projects we build at work. I also really dig the opinions on how the framework should be used, it's wonderful.
3. [Atom](https://github.com/atom/atom) – It didn't take much use of Atom for it to replace all my other editors. I love the power that it gives me and the fact that it's open source and wildly extensible.

## Projects that Have Benefitted Me Most
1. [AutoMapper](http://github.com/automapper/automapper) – I've been using AutoMapper for years now and it's made my life better by saving me thousands of unnecessary keystrokes.
2. [Fixie](http://github.com/fixie/fixie) – Fixie is the test framework I didn't know I needed until I started using it on personal projects. I love having the control of testing my code the way I want to.
3. [MediatR](http://github.com/jbogard/mediatr) – A simple project that implements a simple pattern. Like the previous two, this gets out of the way and makes coding more productive and fun.

## Projects That Have Helped Others
1. [WebApiContrib](http://github.com/webapicontrib) – A few people got together and built a small library of useful patterns that have tons of downloads (for me anyway). I'm judging by download counts that this is a success. And that makes me happy!
2. [Up-For-Grabs.net](http://up-for-grabs.net) – I love spreading the OSS love and this site that my friend Keith built is perfect for it. I'm always looking for more ways to share!
3. [Formo](http://github.com/chrismissal/Formo) – This only makes the list because it's the most popular project that I run by myself. I do like it and still use it so I have to put it in one of these lists.

So that was fun! Thanks again Una for the fantastic question! :smile:

**Comment by ChrisMissal** [comment]
For anybody reading, I'd love to hear what you consider your favorites. Either in these categories, or just in general!
