### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [ChrisMissal/ama#13]

**Comment by ChrisMissal** [comment]
In the past I've spoken at conferences and user groups, but I don't do this as much any more unfortunately. I will present at lunch and learns for work from time to time and I really enjoy those. People tend to open up more into discussion rather than being "talked at" like I've seen in some of my past conf/user group talks.

In terms of one-on-one coaching, my position(s) over the years haven't ever dedicated me to it, but along with the job comes inherent coaching and as long as I'm around that won't go away. Collaboration, teaching, and knowledge sharing is a big part of how I work.

(Apologies for the late reply)
