### ISSUE TITLE
What do you think about star wars?

### ISSUE THREAD

**Issue by robbbz** [ChrisMissal/ama#14]

**Comment by ChrisMissal** [comment]
1. Love the original trilogy.
2. Don't hate the prequels as much as everybody else.
3. I liked most of the new one.

A friend of mine hadn't seen any of them as of November (I believe she plans to watch them in the [Machete Order](http://www.nomachetejuggling.com/2011/11/11/the-star-wars-saga-suggested-viewing-order/), I'm jealous).

Oh, you mean the movies right? Because if not, I do not like wars. :)
